import { MenuItem } from './types';

export const CATEGORIES = [
  'All',
  'Sandwiches',
  'Pasta',
  'Momos',
  'Fries',
  'Veg Starters',
  'Non-Veg Starters',
  'Beverages',
];

export const MOCK_MENU: MenuItem[] = [
  // 1. SANDWICHES
  {
    id: 'sand-1',
    name: 'Bombay Grilled Sandwich',
    description: 'Classic Mumbai-style grilled sandwich with vegetables, cheese and green chutney.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=400&auto=format&fit=crop',
    category: 'Sandwiches',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'sand-2',
    name: 'Paneer Tikka Sandwich',
    description: 'Grilled paneer tikka, onions, peppers and creamy sauce.',
    price: 229,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=400&auto=format&fit=crop',
    category: 'Sandwiches',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'sand-3',
    name: 'Cheese Corn Sandwich',
    description: 'Sweet corn, melted cheese, herbs and creamy seasoning.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1521390188846-e2a39b7ef4a8?q=80&w=400&auto=format&fit=crop',
    category: 'Sandwiches',
    rating: 4,
    popular: false,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'sand-4',
    name: 'Chicken Tandoori Sandwich',
    description: 'Smoky tandoori chicken, onions, lettuce and creamy dressing.',
    price: 249,
    image: 'https://images.unsplash.com/photo-1603064752734-4c48eff53d05?q=80&w=400&auto=format&fit=crop',
    category: 'Sandwiches',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },
  {
    id: 'sand-5',
    name: 'Club Sandwich',
    description: 'Triple-layer sandwich with chicken, egg, vegetables, cheese and house sauce.',
    price: 279,
    image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?q=80&w=400&auto=format&fit=crop',
    category: 'Sandwiches',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },

  // 2. PASTA
  {
    id: 'pasta-1',
    name: 'Alfredo Pasta',
    description: 'Creamy white sauce pasta with herbs, garlic and parmesan.',
    price: 279,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=400&auto=format&fit=crop',
    category: 'Pasta',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'pasta-2',
    name: 'Arrabbiata Pasta',
    description: 'Classic pasta tossed in spicy tomato and garlic sauce.',
    price: 259,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?q=80&w=400&auto=format&fit=crop',
    category: 'Pasta',
    rating: 4,
    popular: false,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'pasta-3',
    name: 'Pink Sauce Pasta',
    description: 'Rich combination of creamy white sauce and tangy tomato sauce.',
    price: 289,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281781?q=80&w=400&auto=format&fit=crop',
    category: 'Pasta',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'pasta-4',
    name: 'White Sauce Pasta',
    description: 'Silky creamy white sauce pasta with herbs and vegetables.',
    price: 269,
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?q=80&w=400&auto=format&fit=crop',
    category: 'Pasta',
    rating: 5,
    popular: false,
    dietary: ['veg'],
    customizable: true,
  },

  // 3. MOMOS
  {
    id: 'momo-1',
    name: 'Classic Veg Momos',
    description: 'Steamed dumplings filled with seasoned vegetables.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?q=80&w=400&auto=format&fit=crop',
    category: 'Momos',
    rating: 4,
    popular: false,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'momo-2',
    name: 'Paneer Momos',
    description: 'Soft dumplings stuffed with spiced paneer and vegetables.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=400&auto=format&fit=crop',
    category: 'Momos',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'momo-3',
    name: 'Schezwan Momos',
    description: 'Spicy momos tossed in fiery Schezwan sauce.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?q=80&w=400&auto=format&fit=crop',
    category: 'Momos',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'momo-4',
    name: 'Chicken Momos',
    description: 'Juicy steamed dumplings filled with seasoned chicken.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?q=80&w=400&auto=format&fit=crop',
    category: 'Momos',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },
  {
    id: 'momo-5',
    name: 'Tandoori Chicken Momos',
    description: 'Chicken momos marinated in tandoori spices and grilled.',
    price: 229,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=400&auto=format&fit=crop',
    category: 'Momos',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },

  // 4. FRIES
  {
    id: 'fries-1',
    name: 'Salted Fries',
    description: 'Crispy golden fries seasoned with sea salt.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?q=80&w=400&auto=format&fit=crop',
    category: 'Fries',
    rating: 4,
    popular: false,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'fries-2',
    name: 'Peri Peri Fries',
    description: 'Crispy fries tossed with spicy peri peri seasoning.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?q=80&w=400&auto=format&fit=crop',
    category: 'Fries',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'fries-3',
    name: 'Cheesy Fries',
    description: 'Crispy fries loaded with creamy melted cheese.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?q=80&w=400&auto=format&fit=crop',
    category: 'Fries',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'fries-4',
    name: 'Mexican Fries',
    description: 'Fries topped with salsa, jalapeños, cheese and Mexican seasoning.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=400&auto=format&fit=crop',
    category: 'Fries',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },

  // 5. VEG STARTERS
  {
    id: 'veg-1',
    name: 'Crispy Corn',
    description: 'Crispy fried corn tossed with herbs, spices and peppers.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=400&auto=format&fit=crop',
    category: 'Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'veg-2',
    name: 'Paneer 65',
    description: 'Crunchy fried paneer tossed with South Indian spices.',
    price: 229,
    image: 'https://images.unsplash.com/photo-1599487405270-87331530e236?q=80&w=400&auto=format&fit=crop',
    category: 'Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'veg-3',
    name: 'Crispy Chilli Paneer',
    description: 'Crispy paneer tossed with peppers, onions and chilli sauce.',
    price: 239,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=400&auto=format&fit=crop',
    category: 'Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: true,
  },
  {
    id: 'veg-4',
    name: 'Veg Crispy',
    description: 'Crispy fried vegetables tossed in a spicy Indo-Chinese sauce.',
    price: 219,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=400&auto=format&fit=crop',
    category: 'Veg Starters',
    rating: 4,
    popular: false,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'veg-5',
    name: 'Honey Chilli Potato',
    description: 'Crispy potato strips glazed with honey, chilli and sesame.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?q=80&w=400&auto=format&fit=crop',
    category: 'Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },

  // 6. NON-VEG STARTERS
  {
    id: 'nonveg-1',
    name: 'Chicken Crispy',
    description: 'Crispy fried chicken tossed in a spicy house sauce.',
    price: 249,
    image: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?q=80&w=400&auto=format&fit=crop',
    category: 'Non-Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },
  {
    id: 'nonveg-2',
    name: 'Chicken 65',
    description: 'South Indian-style spicy crispy fried chicken.',
    price: 259,
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=400&auto=format&fit=crop',
    category: 'Non-Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },
  {
    id: 'nonveg-3',
    name: 'Crispy Chilli Chicken',
    description: 'Crispy chicken tossed with peppers, onions and chilli sauce.',
    price: 269,
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?q=80&w=400&auto=format&fit=crop',
    category: 'Non-Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },
  {
    id: 'nonveg-4',
    name: 'Chicken Wings',
    description: 'Juicy crispy chicken wings served with house dip.',
    price: 289,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?q=80&w=400&auto=format&fit=crop',
    category: 'Non-Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: false,
  },
  {
    id: 'nonveg-5',
    name: 'Chicken Tandoori Tikka',
    description: 'Char-grilled chicken tikka marinated in aromatic Indian spices.',
    price: 299,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=400&auto=format&fit=crop',
    category: 'Non-Veg Starters',
    rating: 5,
    popular: true,
    dietary: ['non-veg'],
    customizable: true,
  },

  // 7. BEVERAGES
  {
    id: 'bev-1',
    name: 'Cold Coffee',
    description: 'Chilled creamy coffee topped with a light foam.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-2',
    name: 'Chocolate Cold Coffee',
    description: 'Rich chilled coffee blended with chocolate.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-3',
    name: 'Hazelnut Cold Coffee',
    description: 'Smooth cold coffee with aromatic hazelnut flavor.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: false,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-4',
    name: 'Oreo Shake',
    description: 'Thick creamy shake blended with Oreo cookies.',
    price: 219,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-5',
    name: 'Chocolate Shake',
    description: 'Rich chocolate milkshake topped with chocolate.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: false,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-6',
    name: 'Mango Shake',
    description: 'Thick mango milkshake made with ripe mango.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-7',
    name: 'Masala Chai',
    description: 'Classic Indian tea brewed with aromatic spices.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-8',
    name: 'Iced Lemon Tea',
    description: 'Refreshing chilled lemon tea.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 4,
    popular: false,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-9',
    name: 'Fresh Lime Soda',
    description: 'Refreshing sparkling lime drink.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
  {
    id: 'bev-10',
    name: 'Mojito',
    description: 'Refreshing mint and lime cooler.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=400&auto=format&fit=crop',
    category: 'Beverages',
    rating: 5,
    popular: true,
    dietary: ['veg'],
    customizable: false,
  },
];
